"""
This type stub file was generated by pyright.
"""

class NonExistentEpBunchTypeError(Exception):
    ...


class IDFMisunderstandingError(Exception):
    ...


class BadlyFormatedIDFError(Exception):
    ...


class InvalidEpBunchError(Exception):
    def __init__(self, expected_key, actual_key) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class InvalidObjectError(Exception):
    def __init__(self, object_: object, name: str, param_name) -> None:
        ...
    
    def message(self): # -> str:
        ...
    


